WIP: Feature/refactor streaming
ecmwf/earthkit-data pull request #371
Opened 2024-04-22 13:27 UTC by sandorkertesz

Fixes #364

2024-04-25 15:12 UTC, iainrussell requested changes
Apart from that suggestion (what do you think @sandorkertesz?), I think this looks really really nice - a good and more intuitive way of doing things.

2024-04-25 15:12 UTC, iainrussell commented on earthkit/data/core/__init__.py
> +    def batched(self, *args):
I wonder if this should be batch() so that it is a verb, like group_by()?

2024-04-25 15:54 UTC, sandorkertesz commented on earthkit/data/core/__init__.py
> +    def batched(self, *args):
I used `batched` and `group_by` because `itertools` uses these names: https://docs.python.org/3/library/itertools.html 
So they might be familiar for Python users. Although `itertools.batched()` is new in Python 3.12

2024-04-25 16:34 UTC, iainrussell commented on earthkit/data/core/__init__.py
> +    def batched(self, *args):
That's a good reason!

2024-05-14 14:05 UTC, tlmquintino approved these changes
Looks good. Thanks for clearing up the interface.

2024-05-15 08:08 UTC, merged